language: ruby
rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - jruby-18mode
  - rbx
  - 1.8.7
install:
  - gem install bundler -v 1.14.4
  - bundle install --jobs=3 --retry=3
script: bundle exec rspec
